version: "3.8"

services:
  db:
    image: postgres:14-alpine
    env_file:
      - .env
    ports:
      - "5438:5432"
    container_name: postgres-apiorders

  redis:
    image: redis:6-alpine
    container_name: redis-apiorders

  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: >
      sh -c "sleep 10 &&
           python manage.py flush --no-input &&
           python manage.py migrate &&
           python manage.py loaddata test_db.json &&
           python manage.py runserver 0.0.0.0:8000"
    container_name: web-apiorders

  celery:
    build: .
    env_file:
      - .env
    command: ['celery', '-A', 'apiorders', 'worker', '-l', 'info']
    depends_on:
#      - web
      - redis
    container_name: celery-apiorders
